name: dev-build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

env:
  DOCKERHUB_SLUG: ${{ secrets.DOCKERHUB_USERNAME }}/diun
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  dev-image:
    runs-on: ubuntu-latest
    if: github.repository != 'crazy-max/diun'  # Only run on forks
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          tags: |
            type=raw,value=dev
            type=ref,event=branch
            type=ref,event=pr
          labels: |
            org.opencontainers.image.title=Diun
            org.opencontainers.image.description=Docker image update notifier
            org.opencontainers.image.vendor=${{ github.repository_owner }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: image-all
          provenance: mode=max
          sbom: true
          pull: true
          push: true
      -
        name: Check manifest
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:dev
      -
        name: Image info
        run: |
          echo "Image pushed to: ${{ env.DOCKERHUB_SLUG }}:dev"
          echo "Additional tags: ${{ steps.meta.outputs.tags }}"